[
	">> EXPERIENCE PROFESSIONNELLE                                         ",
	"                                                                      ",
	"[ Truck2you ] - Responsable Technique                                 ",
	"------------------------------------------------------------          ",
	"  - Conception & structuration BDD, architecture applicative          ",
	"  - Refonte fonctionnelle complète (système d’iframes)                ",
	"  - Livraison de nouvelles features en 2 mois (appli bloquée 1 an)    ",
	"  - Maintenance & développement continu                               ",
	"  - Gestion serveurs OVH (config, sous-domaines, réseau simulé)       ",
	"  - Collaboration avec dirigeant, équipe commerciale et actionnaires  ",
	"  Tech: Symfony, React, React Native, TS, Python Kivy, MariaDB, Git   ",
	"                                                                      ",
	"[ Blue Forest ] - Développeur                                         ",
	"------------------------------------------------------------          ",
	"  - Conception d’un langage informatique descriptif propriétaire      ",
	"  - Développement d’applications web & mobiles (prototype → prod)     ",
	"  - Animation de réunions clients, suivi projet                       ",
	"  - Mise en place de tests (unitaires, E2E, non-régression)           ",
	"  Tech: React, React Native, TS, ArangoDB, Git                        ",
	"                                                                      ",
	"[ Enedis ] - Développeur Full Stack                                   ",
	"------------------------------------------------------------          ",
	"  - Outils internes en JS/PHP pour automatiser les processus métiers  ",
	"  - Maintenance et évolution continue des sites existants             ",
	"  - Refonte et modernisation des anciens outils                       ",
	"  - Définition & supervision de l’architecture projet                 ",
	"  Tech: JS, PHP, HTML/CSS, BDD relationnelles                         ",
	"                                                                      ",
	"[ NOVRH ] - Développeur TMA                                           ",
	"------------------------------------------------------------          ",
	"  - Résolution tickets maintenance applicative                        ",
	"  - Développement d’évolutions selon besoins métiers                  ",
	"  Tech: JavaJEE, JS, MariaDB, Git                                     ",
	"                                                                      ",
	"[ ACSEO ] - Développeur Web                                           ",
	"------------------------------------------------------------          ",
	"  - Maintenance & nouvelles fonctionnalités                           ",
	"  - Mise en place d’un projet Wordpress                               ",
	"  - Modification d’un thème Grav                                      ",
	"  Tech: Symfony, JS, Twig, Docker, Git, Grav, Wordpress               ",
	"                                                                      ",
	"[ Aix-Marseille Université ] - Stage Freelance                        ",
	"------------------------------------------------------------          ",
	"  - Cahier des charges avec le client                                 ",
	"  - Mise en place BDD, environnement, versionning                     ",
	"  - Développement & tests du site                                     ",
	"  - Formation des professeurs                                         ",
	"  Tech: Symfony 2.7, Twig, PHP, JS, CSS, Git, GitLab, Trello          ",
]
